import { Product, Dictionary } from './types';

export const HERO_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuDBhVlhtTMGXTdY_tTiuODm14hNULW9N2ksKXyfacIHtC2mvHYq22HpSZF0x7Fb1k5TNGP8GQEL2qWv582Z6FQE4UxEuIE1UERvLixvtWQytg9LHB6yjHV5h3fLgsl3R8jaYNTHo6r5l8pUm6YNvj-52yqCC-wAJjkk4K26rU-vcOjCH9iU2qoMfi6PAX9f9bSzqUs5s23drfzzI21SUeqLpWcAxsFTusA9CeTt05qjjSzdQKDc0B906jyp35E0axCe8kaVaYwVAMA';

export const PRODUCTS: Product[] = [
  {
    id: "1",
    nameEn: "اس 24 التراء",
    nameAr: "اس 24 التراء",
    descriptionEn: "جوال من شركة سامسونج",
    descriptionAr: "جوال من شركة سامسونج",
    price: "2000﷼سعودي",
    sale_price: "",
    specs: "١.الذاكرة ٢٥٦ ٢.الرام ١٢ ٣.البطارية ٥٠٠٠ ٤.كاميرا ٢٠٠ميجا بكسل ٥.معدل تحديث شاشة ١٢٠هرتز ٦.التقريب ١٠٠اكس ٧.معالج سناب دراجون",
    category: "جوالات",
    image: "https://i.postimg.cc/FsYyr9HL/gsmarena-003-2.jpg",
    images: ["https://i.postimg.cc/FsYyr9HL/gsmarena-003-2.jpg"],
    labelEn: "",
    labelAr: "",
    isFeatured: false,
    colorEn: "",
    colorAr: "",
    specsEn: [],
    specsAr: []
  },
  {
    id: "sheet-2",
    nameEn: "خلاط سيلفر كريست ",
    nameAr: "خلاط سيلفر كريست ",
    descriptionEn: "خلاط كهربائي متعدد الاستعمالات هو جهاز مطبخ متطور يجمع بين الأداء القوي والمرونة، مما يجعله مثاليًا لتحضير العصائر، الشوربات، العجائن، والمزيد. بفضل تصميمه العملي والحديث، يساعد في إنجاز مجموعة متنوعة من المهام بسهولة وكفاءة.",
    descriptionAr: "خلاط كهربائي متعدد الاستعمالات هو جهاز مطبخ متطور يجمع بين الأداء القوي والمرونة، مما يجعله مثاليًا لتحضير العصائر، الشوربات، العجائن، والمزيد. بفضل تصميمه العملي والحديث، يساعد في إنجاز مجموعة متنوعة من المهام بسهولة وكفاءة.",
    price: "70ريال سعودي",
    sale_price: "60ريال سعودي",
    specs: "١.مزود بمحرك عالي الأداء يوفر قوة كبيرة لخلط ومزج جميع المكونات بشكل متساوٍ ٢.شفرات مصنوعة من الفولاذ المقاوم للصدأ تتيح لك خلط، طحن، وفرم المكونات بسهولة ٣.يوفر خيارات سرعة متنوعة تتيح لك التحكم في عملية الخلط للحصول على القوام المثالي ٤.وعاء كبير بسعة مناسبة لتحضير كميات كبيرة من العصائر دفعة واحدة، مصنوع من مواد آمنة وصحية ٥.يمكن استخدامه لمجموعة متنوعة من المهام مثل الخلط، الطحن، الفرم، مما يجعله أداة أساسية في كل مطبخ ٦.4 شفرات حادة ٧.السعة: 2لتر ٨.الجهد:4500 واط ٩.عدد السرعات: 15 ١٠.خلاط كهربائي متعدد الاستعمالات",
    category: "الاجهزة الكهربائية",
    image: "https://i.postimg.cc/SxtYBjLV/614mxm-Aum-AL-AC-UF1000-1000-QL80-FMwebp.webp",
    images: [
      "https://i.postimg.cc/SxtYBjLV/614mxm-Aum-AL-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/bvDSp83D/61CWf83PBYL-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/JhDHMmPz/61Dt-Sr5Bv5L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/sg0Gk1Pw/61s-DIRmlk-OL-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/k56Rq9fn/715pi1u-YH2L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/KYk3xFJS/71k-U1AB7tf-L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/pL15wyQS/71Nq6D3R7CL-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/6Qk2QSmp/71s-ZDDVuoe-L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/cJgt0ZTb/71T8Nd-LOn-PL-AC-UF350-350-QL80-FMwebp.webp",
      "https://i.postimg.cc/3w40Y79q/a-ORm-Wi0tkm-EWme9Sz-HOv3yk4Ppf-Qokrmn-MLV0ifn.webp",
      "https://i.postimg.cc/xT5zP6XQ/IMG-20260702-WA0010.jpg"
    ],
    labelEn: "Special Offer 🔥",
    labelAr: "عرض خاص 🔥",
    isFeatured: true,
    colorEn: "",
    colorAr: "",
    specsEn: [],
    specsAr: []
  },
  {
    id: "sheet-3",
    nameEn: "جهاز ألكتروني لقياس ضغط الدم",
    nameAr: "جهاز ألكتروني لقياس ضغط الدم",
    descriptionEn: "جهاز الكتروني اوتوماتيكي رقمي لقياس ضغط الدم عن طريق الذراع",
    descriptionAr: "جهاز الكتروني اوتوماتيكي رقمي لقياس ضغط الدم عن طريق الذراع",
    price: "49ريال سعودي",
    sale_price: "45ريال سعودي",
    specs: "١.جهاز قياس ضغط الدم مع شاشة LCD كبيرة ومريحة للاستخدام ٢.ووظيفة الكشف عن اضطراب ضربات القلب باستخدام تقنية اي اتش بي، وتصنيف ضغط الدم الخاص وفقًا لمنظمة الصحة العالمية ٣.يحتوي على 99 مجموعة للتخزين(لفردين) ٤.يحتوي على وظيفة صوتية لاستخدام أكثر سهولة ٥.يتميز بمظهر خارجي أنيق كما أنه مناسب للعناية الصحية كل يوم ٦.سهل الاستخدام، حيث يمكنك قياس ضغط الدم في المنزل ٧.خفيف الوزن، يمكنك حمله معك في رحلاتك ٨.إيقاف التشغيل التلقائي: إيقاف التشغيل التلقائي عند عدم التشغيل لمدة دقيقة واحدة ٩.المكونات : كف، خرطوم مطاطي، جراب لحفظ الجهاز، 4 بطاريات",
    category: "الاجهزة الكهربائية",
    image: "https://i.postimg.cc/XJxrgJvh/41cke-I-7NSL-AC-UF1000-1000-QL80-FMwebp.webp",
    images: [
      "https://i.postimg.cc/XJxrgJvh/41cke-I-7NSL-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/FRGYxRKB/41YG9Yc-Ygx-L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/26T1x65G/51cpn2ed-Sr-L-AC-UF1000-1000-QL80-FMwebp.webp",
      "https://i.postimg.cc/JnKsQnhc/IMG-20260129-WA0043(1).jpg"
    ],
    labelEn: "Special Offer 🔥",
    labelAr: "عرض خاص 🔥",
    isFeatured: true,
    colorEn: "",
    colorAr: "",
    specsEn: [],
    specsAr: []
  }
];

export const DICTIONARY: Record<'ar' | 'en', Dictionary> = {
  en: {
    shop: 'Showcase',
    search: 'Search',
    orders: 'Sell Your Item',
    account: 'Special Offers',
    addToCart: 'Add to Cart',
    quantity: 'Quantity',
    cart: 'Shopping Cart',
    checkout: 'Proceed to Checkout',
    subtotal: 'Subtotal',
    total: 'Total Amount:',
    discount: 'Promo Discount',
    shipping: 'Free delivery inside Shabwah province only',
    free: '',
    applyPromo: 'Apply',
    promoCode: 'Coupon: e.g. SMART10',
    promoSuccess: 'SMART coupon applied successfully! (10% Off)',
    invalidPromo: 'Non-active coupon code',
    placeOrder: 'Complete Purchase',
    orderCompleted: 'Order Confirmed!',
    tracking: 'Track Status',
    searchPlaceholder: 'Search high-end items...',
    categoryAll: 'All Collections',
    categoryWatch: 'Watches',
    categoryAudio: 'Audio Eng.',
    categoryAccessory: 'Desk accessories',
    categoryLiving: 'Design Objects',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    shippingInfo: 'Delivery Coordinates',
    fullName: 'Full Name',
    emailAddress: 'Your Email',
    phoneNumber: 'Yemeni Phone (7xxxxxxxx)',
    streetAddress: 'Your current location (for delivery)',
    city: 'City (e.g. Riyadh)',
    postalCode: 'Postal Zip Code',
    paymentDetails: 'Secured Checkout Payment',
    cardNumber: 'Debit / Card Number',
    expiryDate: 'Exp Date (MM/YY)',
    cvv: 'CVV Security code',
    orderStatusPlaced: 'Order Placed',
    orderStatusProcessing: 'In Atelier Preparation',
    orderStatusShipped: 'Shipped via Aramex',
    orderStatusDelivered: 'Delivered Safely',
    emptyCart: 'Your luxury shopping cart is pristine and empty.',
    emptyOrders: 'No orders recorded yet. Begin placing orders!',
    goShopping: 'Explore Collections',
    newArrival: 'New Arrival',
    ofTheWeek: 'Design of the Week',
    exclusiveHeroTitleEn: 'Exclusive Autumn Collection',
    exclusiveHeroTitleAr: 'مجموعة الخريف الحصرية والفريدة',
    heroButtonEn: 'Inquire Now',
    heroButtonAr: 'تسوق الآن',
    shippingFeatureTitleEn: 'Safe & Fast Air Shipping',
    shippingFeatureTitleAr: 'شحن سريع ومجاني آمن بالكامل'
  },
  ar: {
    shop: 'المتجر والمعرض',
    search: 'البحث',
    orders: 'اعرض سلعتك للبيع',
    account: 'العروض الخاصة',
    addToCart: 'إضافة للسلة',
    quantity: 'الكمية المطلوبة',
    cart: 'سلة التسوق والخيارات',
    checkout: 'الانتقال لإنهاء المشتريات',
    subtotal: 'المجموع الفرعي',
    total: 'اجمالي المبلغ:',
    discount: 'خصم الكوبون النشط',
    shipping: 'التوصيل مجاني داخل محافظة شبوة فقط',
    free: '',
    applyPromo: 'تطبيق الخصم',
    promoCode: 'رمز الكوبون: مثال SMART10',
    promoSuccess: 'تم تطبيق كوبون سمارت بنجاح! خصم بقيمة 10٪',
    invalidPromo: 'الكوبون المدخل غير نشط حالياً',
    placeOrder: 'تأكيد وشراء الآن',
    orderCompleted: 'تم إرسال وتأكيد طلبك بنجاح!',
    tracking: 'مراقبة حالة الشحن',
    searchPlaceholder: 'ابحث عن منتجاتنا الفاخرة هنا...',
    categoryAll: 'جميع الأقسام',
    categoryWatch: 'ساعات يد راقية',
    categoryAudio: 'هندسة صوتيات فاخرة',
    categoryAccessory: 'ملحقات ومستلزمات مكتبية',
    categoryLiving: 'تحف ومجسمات فنية',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    shippingInfo: 'إحداثيات وبيانات التوصيل الأساسية',
    fullName: 'الاسم الكامل الثلاثي',
    emailAddress: 'عنوان البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف الجوال اليمني',
    streetAddress: 'مكانك الحالي (من اجل توصيل منتجك اليك)',
    city: 'المدينة المقيم بها (مثال: مستودع الرياض)',
    postalCode: 'الرمز البريدي المقارب',
    paymentDetails: 'بوابة الدفع الآمنة المشفرة',
    cardNumber: 'رقم بطاقة مدى أو الفيزا العالمية',
    expiryDate: 'تاريخ انتهاء الصلاحية والشهر (MM/YY)',
    cvv: 'رمز التحقق الخلفي الثلاثي (CVV)',
    orderStatusPlaced: 'تم استلام وتوثيق الطلب بالمتجر',
    orderStatusProcessing: 'الطلب قيد التجهيز والتلميع',
    orderStatusShipped: 'تم تسليم الشحنة لشركة أرامكس للتو',
    orderStatusDelivered: 'تم توصيل الطلب بنجاح لكم',
    emptyCart: 'سلة تسوقك فارغة وأنيقة تماماً.',
    emptyOrders: 'لم يتم تسجيل أي طلبات بعد. ابدأ أول تجربة توصيل مميزة!',
    goShopping: 'استكشاف المجموعات وتصفح المنتجات',
    newArrival: 'تحفة جديدة',
    ofTheWeek: 'تصميم الأسبوع المميز',
    exclusiveHeroTitleEn: 'Exclusive Autumn Collection',
    exclusiveHeroTitleAr: 'مجموعة الخريف الحصرية والفريدة',
    heroButtonEn: 'Inquire Now',
    heroButtonAr: 'تسوق الآن',
    shippingFeatureTitleEn: 'Safe & Fast Air Shipping',
    shippingFeatureTitleAr: 'شحن سريع ومجاني آمن بالكامل'
  }
};
